---
services:
  perceived-temp-service:
    container_name: perceived-temp-service
    image: svenschmidt1502/perceived-temp:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_PRODUCER_TOPIC=${KAFKA_PRODUCER_TOPIC}'
      - 'KAFKA_TEMP_TOPIC=${KAFKA_TEMP_TOPIC}'
      - 'KAFKA_HUMIDITY_TOPIC=${KAFKA_HUMIDITY_TOPIC}'
    deploy:
      replicas: 1